In [1]:
import tensorflow as tf
print(tf.__version__)

2.5.0


In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scalar.ndim

0

In [4]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [5]:
vector.ndim

1

In [6]:
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [7]:
matrix.ndim

2

In [8]:
matrix2 = tf.constant([[10.,7.],[7.,10.]],dtype=tf.float16)
matrix2

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.]], dtype=float16)>

In [9]:
matrix2.ndim

2

In [10]:
tensor = tf.constant([[[1,2,3],[4,5,6]],
                     [[7,8,9],[10,11,12]],
                     [[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [11]:
tensor.ndim

3

In [12]:
tf.constant([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18],shape=(3,2,3))

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [13]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [14]:
import numpy as np

In [15]:
tf.constant(np.arange(1,55),shape=(2,3,3,3)).ndim

4

In [16]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [17]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [18]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [22]:
not_shuffled = tf.constant([[10,7],
                          [3,4],
                          [2,5]])

not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [59]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [60]:
import numpy as np

In [63]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [65]:
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [69]:
numpy_A = np.arange(1, 25, dtype=np.int32)
A = tf.constant(numpy_A,shape=(2,3,4))
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24]),
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>)

In [71]:
A.shape, A.ndim, tf.size(A)

(TensorShape([2, 3, 4]), 3, <tf.Tensor: shape=(), dtype=int32, numpy=24>)

In [72]:
A[0]

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])>

In [73]:
A[1]

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])>

In [75]:
A[0][1]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([5, 6, 7, 8])>

In [78]:
B = tf.zeros(shape=(2,3,4,5))
B

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [79]:
tf.size(B)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [81]:
tf.size(B).numpy()

120

In [82]:
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [85]:
A[:2,:1,:2]

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[ 1,  2]],

       [[13, 14]]])>

In [86]:
A[:1,:2,:2]

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [5, 6]]])>

In [89]:
extra_dim_A = A[..., tf.newaxis]

In [90]:
extra_dim_A.ndim

4

In [92]:
A.ndim

3

In [96]:
extra_dim_A

<tf.Tensor: shape=(2, 3, 4, 1), dtype=int32, numpy=
array([[[[ 1],
         [ 2],
         [ 3],
         [ 4]],

        [[ 5],
         [ 6],
         [ 7],
         [ 8]],

        [[ 9],
         [10],
         [11],
         [12]]],


       [[[13],
         [14],
         [15],
         [16]],

        [[17],
         [18],
         [19],
         [20]],

        [[21],
         [22],
         [23],
         [24]]]])>

In [98]:
tf.expand_dims(extra_dim_A,axis=-1)

<tf.Tensor: shape=(2, 3, 4, 1, 1), dtype=int32, numpy=
array([[[[[ 1]],

         [[ 2]],

         [[ 3]],

         [[ 4]]],


        [[[ 5]],

         [[ 6]],

         [[ 7]],

         [[ 8]]],


        [[[ 9]],

         [[10]],

         [[11]],

         [[12]]]],



       [[[[13]],

         [[14]],

         [[15]],

         [[16]]],


        [[[17]],

         [[18]],

         [[19]],

         [[20]]],


        [[[21]],

         [[22]],

         [[23]],

         [[24]]]]])>

In [100]:
tf.multiply(A, 10)

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 10,  20,  30,  40],
        [ 50,  60,  70,  80],
        [ 90, 100, 110, 120]],

       [[130, 140, 150, 160],
        [170, 180, 190, 200],
        [210, 220, 230, 240]]])>

In [108]:
tensor = tf.constant([[10,7],
                     [3,4]])

In [109]:
tensor.shape

TensorShape([2, 2])

In [110]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [111]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [112]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]])>

In [115]:
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [114]:
tf.reshape(A,shape=(4,3,2))

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])>

In [116]:
tf.transpose(A)

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])>

In [118]:
tf.tensordot(tensor, tensor,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [123]:
tf.tensordot(tensor, tensor,axes=0)

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[100,  70],
         [ 30,  40]],

        [[ 70,  49],
         [ 21,  28]]],


       [[[ 30,  21],
         [  9,  12]],

        [[ 40,  28],
         [ 12,  16]]]])>

In [121]:
tensor, tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>)

In [124]:
tf.tensordot(tensor, tensor,axes=2)

<tf.Tensor: shape=(), dtype=int32, numpy=174>

In [126]:
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [133]:
tf.cast(A,dtype=tf.float16)

<tf.Tensor: shape=(2, 3, 4), dtype=float16, numpy=
array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]],

       [[13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]]], dtype=float16)>

In [162]:
B = tf.constant(np.random.randint(1,100,50))

In [163]:
B

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([81, 75,  2, 47, 45, 61, 64, 97, 60, 93, 32,  4, 27, 63,  7, 69, 13,
       58, 94, 78, 11, 59, 45, 42, 36, 45, 20, 40, 39, 94, 31, 72, 19, 73,
       88, 72, 65, 30, 23, 93, 70, 19, 92, 72, 53, 69, 99, 73, 97, 97])>

In [164]:
B[tf.argmax(B)]

<tf.Tensor: shape=(), dtype=int32, numpy=99>

In [165]:
tf.reduce_max(B)

<tf.Tensor: shape=(), dtype=int32, numpy=99>

In [166]:
B[tf.argmin(B)]

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [167]:
tf.reduce_min(B)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [168]:
tf.reduce_mean(B)

<tf.Tensor: shape=(), dtype=int32, numpy=56>

In [169]:
tf.reduce_sum(B)

<tf.Tensor: shape=(), dtype=int32, numpy=2808>

In [171]:
tf.math.reduce_std(tf.cast(B,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.200964>

In [173]:
tf.math.reduce_variance(tf.cast(B,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=795.29443>

In [176]:
tf.argmax(B,axis=0)

<tf.Tensor: shape=(), dtype=int64, numpy=46>

In [181]:
extra_dim_A.ndim

4

In [178]:
A_squeezed = tf.squeeze(extra_dim_A)

In [180]:
A_squeezed.ndim

3

In [182]:
some_list = [0,1,2,3,4]
tf.one_hot(some_list, depth=5, on_value='yes', off_value='no')

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'yes', b'no', b'no', b'no', b'no'],
       [b'no', b'yes', b'no', b'no', b'no'],
       [b'no', b'no', b'yes', b'no', b'no'],
       [b'no', b'no', b'no', b'yes', b'no'],
       [b'no', b'no', b'no', b'no', b'yes']], dtype=object)>

In [183]:
some_list = [0,1,2,3,4]
tf.one_hot(some_list, depth=5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [184]:
some_list = [0,1,2,3,4]
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [186]:
C = tf.range(1,10)
C

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [187]:
tf.square(C)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [190]:
tf.sqrt(tf.cast(C,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [192]:
tf.math.log(tf.cast(C,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [193]:
numpy_D = tf.constant(np.array([3., 7., 10.]))
tensor_D = tf.constant([3., 7., 10.])

In [194]:
numpy_D.dtype, tensor_D.dtype

(tf.float64, tf.float32)

In [200]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [201]:
!nvidia-smi

Tue Jul 19 00:38:10 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 516.59       Driver Version: 516.59       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   41C    P8     3W /  N/A |   2426MiB /  4096MiB |      6%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------